linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Printf
      - fmt.Println
      - fmt.Fprintf
      - fmt.Fprintln
      - (github.com/go-kit/log.Logger).Log
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - yodaStyleExpr
      - unnamedResult
  gosec:
    excludes:
      - G107
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

run:
  issues-exit-code: 1
